# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  name: Casa
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  unit_system: metric
  time_zone: Europe/Rome
  external_url: !secret external_url
  internal_url: !secret internal_url
  customize: !include customize.yaml
  allowlist_external_dirs: #Serve per far vedere il db dal sensore della dimensione
   - /config


http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

default_config:

frontend:
  themes: !include_dir_merge_named themes

hacs:
  token: !secret hacs_token

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

#logger:
#  default: info
#  logs:
#    custom_components.hacs: debug
#    hacs: debug
#    queueman: debug
#    AIOGitHubAPI: debug

mqtt:
    broker: core-mosquitto
    username: !secret mqtt_username
    password: !secret mqtt_password 

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

light: !include lights.yaml         
sensor: !include sensors.yaml       
switch: !include switches.yaml      
cover: !include covers.yaml        

history: !include history.yaml
shell_command: !include shellCommands.yaml

mobile_app:
discovery:
ios:
cloud:
shopping_list:
wake_on_lan:
smartir:
    
climate:
  - platform: generic_thermostat
    name: Riscaldamento
    heater: switch.switch_sonoff_riscaldamento
    target_sensor: sensor.temperatura_corridoio
    min_temp: 15
    max_temp: 30
    ac_mode: False
    target_temp: 17
    cold_tolerance: 0.5
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 16
    
  - platform: smartir
    name: Condizionatore Alessio
    device_code: 1380
    controller_data: remote.broadlink_rm3mini_alessio_remote
    temperature_sensor: sensor.temperatura_camera_alessio
    humidity_sensor: sensor.temperatura_camera_alessio
    power_sensor: sensor.temperatura_camera_alessio
    
    
    
    
    
    
    
    
#monitor_docker:
#  - name: Docker
#    containers:
#      - appdaemon
#      - db-dsmr
#      - db-hass
#      - deconz
#      - dsmr
#      - hass
#      - influxdb
#      - mosquitto
#      - nodered
#      - unifi
#    rename:
#      db-dsmr: "Database DSMR-Reader"
#      appdaemon: AppDaemon
#      db-hass: Database Home Assistant
#      dsmr: "DSMR-Reader"
#      deconz: DeCONZ
#      hass: Home Assistant
#      influxdb: InfluxDB
#      mosquitto: Mosquitto
#      nodered: "Node-RED"
#      unifi: UniFi
#    monitored_conditions:
#      - version
#      - containers_running
#      - containers_total
#      - state
#      - status
#      - memory